services:
  postgres:
    image: postgres:15
    container_name: treino_pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user_root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: data
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
